'use client';
import {useState,useEffect} from 'react';
import {ArrowUpRight,ArrowRight,BookOpen,LayoutGrid,Grid2X2,List,ChevronDown,Check} from 'lucide-react';
import {Button} from '../components/ui/button';
import {passages} from '../lib/vocabulary';
import type {WordProgress} from '../lib/study';
import {findResumableSession,type ResumableSession} from '../lib/session-policy';
type Session=ResumableSession;
type Props={progress:Record<string,WordProgress>;sessions:Session[];loading:boolean;busy:boolean;start:(mode?:string,id?:string)=>void;restart:(id:string)=>void;resume:(id:string)=>void;controls:React.ReactNode};
export default function ReadingLibrary({progress,sessions,loading,busy,start,restart,resume,controls}:Props){
 const [layout,setLayout]=useState('panorama'),[year,setYear]=useState(2026),[listYear,setListYear]=useState('all'),[wordList,setWordList]=useState<string|null>(null);
 useEffect(()=>{try{const p=localStorage.getItem('reading-layout');if(['cards','panorama','list'].includes(p||''))setLayout(p!);}catch{}},[]);
 function changeLayout(l:string){setLayout(l);setWordList(null);try{localStorage.setItem('reading-layout',l);}catch{}}
 const years=[...new Set(passages.map(p=>p.year))].sort((a,b)=>b-a);
 const completed=sessions.filter(s=>s.status==='completed'&&s.mode==='passage');
 const rounds=(id:string)=>completed.filter(s=>s.title===id.split('-')[0]+' 年 · Text '+id.split('-')[1]).length;
 const fullRounds=(id:string)=>completed.filter(s=>s.title===id.split('-')[0]+' 年 · Text '+id.split('-')[1]&&s.total===passages.find(p=>p.id===id)?.words.length).length;
 const seen=(id:string)=>passages.find(p=>p.id===id)!.words.filter(w=>progress[w.id]).length;
 const wrong=(id:string)=>passages.find(p=>p.id===id)!.words.filter(w=>progress[w.id]?.mistakes>0&&progress[w.id].streak<3).length;
 const active=findResumableSession(sessions);
 const unfinished=(id:string)=>findResumableSession(sessions,id);
 const enter=(id:string)=>{const pending=unfinished(id);if(pending)resume(pending.id);else start('passage',id);};
 const practiced=passages.filter(p=>seen(p.id)>0).length;
 const pending=Object.values(progress).filter(p=>p.mistakes>0&&p.streak<3).length;
 const visible=passages.filter(p=>listYear==='all'||p.year===Number(listYear)).sort((a,b)=>b.year-a.year||a.text-b.text);
 return <>
 <section className="library-intro"><div><p className="eyebrow"><span className="tiny-line"/> THE READING COLLECTION / 英语一</p><h1>读过。记住。<br/><span>再见时，不再陌生。</span></h1><p className="intro-description">让单词回到阅读里。每一篇，都留下你的学习轨迹。</p></div><div className="intro-index"><span>2010<span className="index-dash">—</span>2026</span><div className="index-bottom"><b>68</b><span>篇真题阅读<br/>2,619 个原文词条</span></div></div></section>
 <div className="learning-strip"><div><span>我的阅读足迹</span><b>{loading?'—':practiced}<small>/ 68 篇</small></b></div><div><span>已练习词条</span><b>{loading?'—':Object.keys(progress).length}<small>/ 2,619</small></b></div><div><span>已完成练习</span><b>{loading?'—':completed.length}<small>轮</small></b></div><div><span>待巩固错词</span><b className="orange">{loading?'—':pending}<small>个</small></b></div><span className="strip-caption">EVERY SMALL STEP COUNTS.</span></div>
 {active&&<div className="resume-banner"><div><span className="resume-label">CONTINUE READING</span><b>{active.title}</b><p>上次停在第 {active.answered} / {active.total} 词，接着来吧。</p></div><Button className="primary" disabled={busy} onClick={()=>resume(active.id)}>继续练习 <ArrowRight size={16}/></Button></div>}
 <section className="collection-section"><div className="collection-heading"><div><span className="section-index">01 / COLLECTION</span><h2>你的阅读书架</h2></div><div className="layout-switch" aria-label="阅读布局">{([['panorama','复习全景',Grid2X2],['cards','阅读卡片',LayoutGrid],['list','紧凑清单',List]] as const).map(([id,label,Icon])=><button key={id} aria-pressed={layout===id} className={layout===id?'selected':''} onClick={()=>changeLayout(id)}><Icon size={16}/><span>{label}</span></button>)}</div></div>
 <div className="collection-toolbar"><div className="view-explanation">{layout==='panorama'?<>把 17 年阅读铺开，看见每一篇的积累。</>:layout==='cards'?'一次专注一个年份，慢慢读，反复记。':'少一点翻找，快速找到下一篇。'}</div>{controls}</div>
 {layout==='cards'?<div className="year-tabs">{years.map(y=><button key={y} aria-pressed={year===y} className={year===y?'selected':''} onClick={()=>setYear(y)}>{y}</button>)}</div>:<div className="overview-tools"><div className="mini-filter" role="group" aria-label="筛选阅读年份"><button aria-pressed={listYear==='all'} className={listYear==='all'?'selected':''} onClick={()=>setListYear('all')}>全部年份</button>{years.map(y=><button key={y} aria-pressed={listYear===String(y)} className={listYear===String(y)?'selected':''} onClick={()=>setListYear(String(y))}>{y}</button>)}</div><div className="legend"><span><i/>尚未练习</span><span><i className="touched"/>有过练习</span><span><i className="repeated"/>已复习 3 轮以上</span></div></div>}
 {layout==='panorama'&&<><div className="panorama-scroll"><div className="panorama"><div className="panorama-header"><span>年份 / YEAR</span>{[1,2,3,4].map(n=><span key={n}>TEXT 0{n}<small>阅读 {['一','二','三','四'][n-1]}</small></span>)}</div>{years.filter(y=>listYear==='all'||String(y)===listYear).map(y=><div className="panorama-row" key={y}><div className="panorama-year"><b>{y}</b><span>{passages.filter(p=>p.year===y&&seen(p.id)>0).length} / 4 篇已开始</span></div>{passages.filter(p=>p.year===y).map(p=>{const r=rounds(p.id),n=seen(p.id),m=wrong(p.id),pending=unfinished(p.id);return <div className="reading-cell-wrap" key={p.id}><button className={'reading-cell '+(r>=3?'well-read':n?'has-read':'')} disabled={busy||loading} onClick={()=>enter(p.id)} aria-label={y+' 年 Text '+p.text+'，复习 '+r+' 轮，'+(pending?'继续练习，已答 '+pending.answered+' / '+pending.total:'开始练习')}><div className="cell-number"><strong>{loading?'—':String(r).padStart(2,'0')}</strong><span>轮复习</span><ArrowUpRight size={16}/></div><div className="cell-detail"><span>{n} / {p.words.length} 词</span><span className={m?'cell-mistakes':''}>{pending?'继续 '+pending.answered+'/'+pending.total:m?m+' 错词':n?'已开始':'未开始'}</span></div><div className="cell-progress"><i style={{width:n/p.words.length*100+'%'}}/></div></button>{pending&&<button className="cell-restart" disabled={busy} aria-label={y+' 年 Text '+p.text+' 重新开始新一轮'} onClick={()=>restart(p.id)}>新一轮</button>}</div>})}</div>)}</div></div><p className="count-note">轮次统计：完成一轮按篇刷词计 1 轮（含 10 / 20 词练习）；未完成与跨篇错词练习不计入。进度条表示已练习词条覆盖率。</p></>}
 {layout==='cards'&&<><div className="year-heading"><h3>{year}<span>英语一 · 四篇阅读</span></h3><span>精选原文释义</span></div><div className="passage-grid">{passages.filter(p=>p.year===year).map(p=><article className="passage-card" key={p.id}><div className="card-top"><span className="text-number">READING / 0{p.text}</span><span className={'badge '+(rounds(p.id)?'green':'')}>{rounds(p.id)?'复习 '+rounds(p.id)+' 轮':'等待翻开'}</span></div><div className="reading-card-title"><h2>Text {p.text}</h2><span>阅读理解 {['一','二','三','四'][p.text-1]}</span></div><p className="word-preview">{p.words.slice(0,3).map(w=>w.word).join(' · ')}</p><div className="card-meta"><span>{p.words.length} 个词条 · 约 {Math.ceil(p.words.length/5)} 分钟</span><span>{wrong(p.id)?wrong(p.id)+' 个待巩固':'完整练完 '+fullRounds(p.id)+' 轮'}</span></div><div className="progress-track"><i style={{width:seen(p.id)/p.words.length*100+'%'}}/></div><div className="card-bottom"><button className="plain meta-link" onClick={()=>setWordList(wordList===p.id?null:p.id)}>查看词表 <span>{seen(p.id)}/{p.words.length}</span></button><button className="start-link" disabled={busy||loading} onClick={()=>enter(p.id)}>{unfinished(p.id)?'继续 '+unfinished(p.id)!.answered+'/'+unfinished(p.id)!.total:seen(p.id)?'再读一遍':'开始刷词'} <ArrowUpRight size={18}/></button></div>{unfinished(p.id)&&<button className="plain restart-link" disabled={busy} onClick={()=>restart(p.id)}>重新开始新一轮 · 原记录保留</button>}</article>)}</div></>}
 {layout==='list'&&<div className="compact-list"><div className="compact-header"><span>阅读篇目</span><span>词条进度</span><span>复习轮次</span><span>待巩固</span><span/></div>{visible.map(p=><div className="compact-row" key={p.id}><div><span>{p.year}</span><b>Text {p.text}</b></div><span>{seen(p.id)} <small>/ {p.words.length}</small></span><strong>{rounds(p.id)} <small>轮</small></strong><span className={wrong(p.id)?'orange':''}>{wrong(p.id)} 词</span><button className="start-link" disabled={busy||loading} onClick={()=>enter(p.id)}>{unfinished(p.id)?"继续":"练习"} <ArrowUpRight size={17}/></button></div>)}</div>}
 {wordList&&<section className="word-list"><div className="section-title"><h2>{wordList.split('-')[0]} · Text {wordList.split('-')[1]} 词表</h2><Button variant="ghost" onClick={()=>setWordList(null)}>收起 <ChevronDown size={16}/></Button></div>{passages.find(p=>p.id===wordList)?.words.map(w=><div className="word-row" key={w.id}><strong>{w.word}</strong><span>{w.meaning}</span><small>PDF {w.page} 页</small></div>)}</section>}
 </section>
 </>;
}

