'use client';

import {useEffect,useState} from 'react';
import type {Statistics} from '../lib/statistics';
import {byId,passages} from '../lib/vocabulary';
import Meaning from './meaning';
import './statistics.css';

type Props={start:(mode?:string,passageId?:string,wordIds?:string[])=>void;read:(passageId:string,wordId?:string)=>void;busy:boolean};
const count=(n:number)=>n.toLocaleString('zh-CN');
const rate=(n:number|null)=>n===null?'—':`${Math.round(n*100)}%`;
const duration=(ms:number)=>ms<60000?`${Math.round(ms/1000)} 秒`:`${Math.round(ms/60000)} 分钟`;
const dateLabel=(value:number|null)=>value===null?'尚未练习':new Date(value).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai',month:'long',day:'numeric'});
function Ring({seen,strong,total}:{seen:number;strong:number;total:number}){return <svg viewBox="0 0 44 44" aria-hidden="true"><circle cx="22" cy="22" r="18" className="observatory-ring-track"/><circle cx="22" cy="22" r="18" pathLength="100" strokeDasharray={`${total?seen/total*100:0} 100`} className="observatory-ring-seen" opacity={seen?1:0}/><circle cx="22" cy="22" r="12" pathLength="100" strokeDasharray={`${total?strong/total*100:0} 100`} className="observatory-ring-strong" opacity={strong?1:0}/><circle cx="22" cy="22" r="2" className={seen?'observatory-star lit':'observatory-star'}/></svg>}
export default function StatisticsPanel({start,read,busy}:Props){
 const [days,setDays]=useState<7|30|90>(30),[data,setData]=useState<Statistics|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[retry,setRetry]=useState(0),[selectedReading,setSelectedReading]=useState<string|null>(null),[selectedDay,setSelectedDay]=useState<string|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch(`/api/statistics?days=${days}`,{cache:'no-store',signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('暂时无法读取学习记录');return response.json() as Promise<Statistics>}).then(result=>{if(controller.signal.aborted)return;setData(result);setLoading(false)}).catch(reason=>{if(controller.signal.aborted)return;setError(reason instanceof Error?reason.message:'暂时无法读取学习记录');setLoading(false)});return()=>controller.abort()},[days,retry]);
 const reading=data?.readings.find(item=>item.id===selectedReading),day=data?.calendar.find(item=>item.date===selectedDay),summary=data?.summary;
 const years=data?[...new Set(data.readings.map(item=>item.year))]:[];
 const difference=summary&&summary.rememberRate!==null&&summary.previousRememberRate!==null?(summary.rememberRate-summary.previousRememberRate)*100:null;
 const maxRhythm=Math.max(1,...(data?.rhythm.map(item=>item.attempts)??[]));
 function openWord(id:string){const passage=passages.find(item=>item.words.some(word=>word.id===id));if(passage)read(passage.id,id)}
 return <div className="observatory">
  <header className="observatory-intro"><div><p className="observatory-kicker"><span/> THE MEMORY OBSERVATORY</p><h1>记忆观测站<span>每一次想起，都有迹可循。</span></h1><p className="observatory-caption">把练习留下的轨迹，变成下一次出发的方向。</p></div><div className="observatory-period"><span>观察窗口 · 含今天</span><div role="group" aria-label="统计时间范围">{([7,30,90] as const).map(value=><button key={value} aria-pressed={days===value} onClick={()=>{if(value===days)return;setLoading(true);setError('');setDays(value)}}>{value} 天</button>)}</div></div></header>
  {error?<div className="observatory-state" role="alert"><h2>记录还在，连接暂时中断。</h2><p>{error}</p><button className="observatory-button" onClick={()=>{setLoading(true);setError('');setRetry(value=>value+1)}}>重新读取 ↗</button></div>:loading?<div className="observatory-state" role="status"><div className="observatory-loading-orbit"/><h2>正在展开你的记忆轨迹</h2><p>读取真实练习记录中…</p></div>:data&&summary?<>
  <section className="observatory-metrics" aria-label={`近 ${days} 天学习概览`}><div className="observatory-primary-metric"><span className="observatory-label">近 {days} 天 · 回忆作答</span><strong>{count(summary.attempts)}<small>次</small></strong><p>{summary.attempts?`遇见 ${count(summary.uniqueWords)} 个词，其中 ${count(summary.newWords)} 个是初次练习。`:'第一条轨迹，等待你亲手点亮。'}</p></div><div className="observatory-secondary-metric"><span className="observatory-label">自评「没忘记」占比</span><strong>{rate(summary.rememberRate)}</strong><p>{difference===null?'上个同长窗口暂无可比数据':`比上个 ${days} 天${difference>=0?'增加':'减少'} ${Math.abs(difference).toFixed(1)} 个百分点`}</p></div><div className="observatory-small-metrics"><div><span>近 {days} 天练习天数</span><strong>{summary.activeDays}<small>天</small></strong></div><div><span>近 {days} 天回忆作答用时</span><strong>{duration(summary.duration)}</strong></div></div></section>
  <p className="observatory-method">统计来自你对回忆的自我判断，并非客观正确率。作答用时不等于在线时长。</p>
  {!summary.totalSeen&&<div className="observatory-first"><div><strong>一片尚未点亮的星空，也是一张出发地图。</strong><p>从一篇阅读开始。完成回忆作答后，覆盖、热力图和薄弱词会在这里逐渐出现。</p></div><button className="observatory-button" disabled={busy} onClick={()=>start('passage',passages[0].id)}>开始第一次练习 ↗</button></div>}
  <section className="observatory-sky" aria-labelledby="observatory-sky-title"><div className="observatory-section-heading"><div><p className="observatory-kicker">01 / READING CONSTELLATION</p><h2 id="observatory-sky-title">阅读星图</h2><p>每篇阅读是一颗星。外环记录相遇，内环记录巩固。</p></div><div className="observatory-sky-total"><strong>{count(summary.totalSeen)}<span> / {count(summary.totalWords)}</span></strong><span>累计已练词条 · 按篇计数</span></div></div>
   <div className="observatory-sky-legend"><span><i/>已练覆盖</span><span><i/>已巩固</span><span>连续 3 次自评没忘记 = 已巩固</span></div>
   <div className="observatory-star-map">{years.map(year=><div className="observatory-star-year" key={year}><b>{year}</b>{data.readings.filter(item=>item.year===year).map(item=><button key={item.id} className={selectedReading===item.id?'selected':''} aria-pressed={selectedReading===item.id} aria-label={`${item.year} 年 Text ${item.text}，已练 ${item.seen} / ${item.total} 词，已巩固 ${item.strengthened} 词，查看详情`} onClick={()=>setSelectedReading(selectedReading===item.id?null:item.id)}><Ring seen={item.seen} strong={item.strengthened} total={item.total}/><span>Text {item.text}</span></button>)}</div>)}</div>
   {reading&&<div className="observatory-reading-detail" role="region" aria-label={`${reading.year} 年 Text ${reading.text} 详情`}><div><span className="observatory-kicker">SELECTED READING</span><h3>{reading.year}<span>Text {reading.text}</span></h3><p>最近练习：{dateLabel(reading.lastAt)} · 累计完成 {reading.rounds} 轮</p></div><dl><div><dt>累计覆盖</dt><dd>{reading.seen}/{reading.total}</dd></div><div><dt>已巩固 / 待巩固</dt><dd>{reading.strengthened} / {reading.pending}</dd></div><div><dt>近 {days} 天作答 / 自评没忘记</dt><dd>{reading.periodAttempts} / {rate(reading.periodRememberRate)}</dd></div></dl><div className="observatory-detail-actions"><button className="observatory-button" disabled={busy} onClick={()=>start('passage',reading.id)}>继续这篇 ↗</button><button className="observatory-text-button" onClick={()=>read(reading.id)}>阅读原文</button><button className="observatory-text-button" onClick={()=>setSelectedReading(null)}>收起详情</button></div></div>}
   <div className="observatory-sky-footer"><span>累计已巩固 <b>{count(summary.strengthened)}</b> 词 · 待巩固 <b>{count(summary.pending)}</b> 词</span><button disabled={busy||!summary.due} onClick={()=>start('due')}>到期复习 {count(summary.due)} 词 <span>↗</span></button></div>
  </section>
  <div className="observatory-middle"><section className="observatory-calendar" aria-labelledby="observatory-calendar-title"><div className="observatory-section-heading"><div><p className="observatory-kicker">02 / A LITTLE, OFTEN</p><h2 id="observatory-calendar-title">让记忆，有日常</h2></div><span className="observatory-section-note">近 84 天 · 独立于观察窗口</span></div><div className="observatory-streak"><strong>{summary.currentStreak}<span>天</span></strong><p>当前连续练习<br/><span>历史最长 {summary.longestStreak} 天</span></p></div><div className="observatory-heatmap" aria-label="近84天练习热力图">{data.calendar.map(item=><button key={item.date} data-level={item.attempts===0?0:item.attempts<10?1:item.attempts<30?2:item.attempts<60?3:4} aria-label={`${item.date}，${item.attempts} 次作答`} aria-pressed={selectedDay===item.date} title={`${item.date} · ${item.attempts} 次作答 · 自评没忘记 ${item.remembered} 次`} onClick={()=>setSelectedDay(item.date)}/>)}</div><div className="observatory-heatmap-legend"><span>{data.calendar[0]?.date.slice(5).replace('-','/')}</span><span>少 <i data-level="0"/><i data-level="1"/><i data-level="2"/><i data-level="3"/><i data-level="4"/> 多</span><span>{data.calendar.at(-1)?.date.slice(5).replace('-','/')}</span></div><div className="observatory-day-detail" aria-live="polite">{day?<><b>{day.date}</b><span>{day.attempts} 次作答 · {day.remembered} 次没忘记 · {day.forgotten} 次忘记</span><span>初次练习 {day.newWords} 词 · 回忆作答 {duration(day.duration)}</span></>:<span>点选一个日子，翻开那天的练习记录。</span>}</div></section>
  <section className="observatory-rhythm" aria-labelledby="observatory-rhythm-title"><div className="observatory-section-heading"><div><p className="observatory-kicker">03 / YOUR DAILY RHYTHM</p><h2 id="observatory-rhythm-title">你在什么时候想起</h2></div></div><p className="observatory-caption">近 {days} 天 · 北京时间 · 柱高表示作答次数</p><div className="observatory-rhythm-chart">{data.rhythm.map(item=><div key={item.startHour} className="observatory-rhythm-column"><span>{item.attempts||'—'}</span><div className="observatory-rhythm-track"><i style={{height:`${item.attempts/maxRhythm*100}%`}}/></div><b>{item.label}</b><small>{rate(item.rememberRate)}</small></div>)}</div><p className="observatory-method">下方百分比为该时段自评没忘记占比。记录只描述过去，不预测最佳学习时间。</p></section></div>
  <div className="observatory-word-sections"><section className="observatory-difficult"><div className="observatory-section-heading"><div><p className="observatory-kicker">04 / WORTH ANOTHER LOOK</p><h2>还想再见你一面</h2><p>近 {days} 天忘记过、目前仍待巩固的词</p></div><button className="observatory-text-button" disabled={busy||!data.difficult.length} onClick={()=>start('wrong',undefined,data.difficult.map(item=>item.wordId))}>练这组词 ↗</button></div>{data.difficult.length?<div className="observatory-word-list">{data.difficult.slice(0,8).map((item,index)=>{const word=byId.get(item.wordId);return <article key={item.wordId}><span className="observatory-word-index">{String(index+1).padStart(2,'0')}</span><div><button onClick={()=>openWord(item.wordId)}>{word?.word??item.wordId}</button><p><Meaning text={word?.meaning}/></p></div><span className="observatory-word-misses">忘记 {item.mistakes} 次<small>连续没忘记 {item.streak} 次</small></span></article>})}</div>:<div className="observatory-quiet"><span>∅</span><p>{summary.attempts?'这个窗口内，没有仍待巩固的遗忘词。':'完成练习后，需要再见的词会留在这里。'}</p></div>}</section>
  <section className="observatory-comebacks"><p className="observatory-kicker">05 / FOUND AGAIN</p><div className="observatory-comeback-title"><h2>重新想起的词</h2><span>↗</span></div><p className="observatory-caption">曾经忘记，如今连续 3 次自评没忘记。</p><strong className="observatory-comeback-count">{count(summary.recovered)}<small>个 · 累计</small></strong>{data.comebacks.length?<div className="observatory-recovered-words">{data.comebacks.slice(0,9).map(item=><button key={item.wordId} onClick={()=>openWord(item.wordId)} title={byId.get(item.wordId)?.meaning}>{byId.get(item.wordId)?.word??item.wordId}<span>↗</span></button>)}</div>:<p className="observatory-comeback-empty">遗忘不是终点。<br/>那些重新熟悉的词，会在这里与你重逢。</p>}</section></div>
  {!!data.milestones.length&&<section className="observatory-milestones" aria-label="真实练习里程碑"><span className="observatory-kicker">沿途的刻度</span>{data.milestones.map(item=><div key={item.id} data-achieved={item.achieved}><span aria-hidden="true">{item.achieved?'✦':'◇'}</span><div><b>{item.label}</b><small>{item.achieved?'已达成':`${count(item.current)} / ${count(item.target)}`}</small></div></div>)}</section>}
  <div className="observatory-bottom-note">以真实记录为刻度，以每一次重逢为进步。<span>MEMORY IS A PRACTICE.</span></div>
  </>:null}
 </div>
}


